services:
  # База данных PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: myapp-postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - myapp-network

  # Серверное приложение
  server:
    build:
      context: ./packages/server
      dockerfile: Dockerfile
    container_name: myapp-server
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: ${NODE_ENV}
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - myapp-network

  # Клиентское приложение
  client:
    build:
      context: ./packages/client
      dockerfile: Dockerfile
      target: development
    container_name: myapp-client
    env_file:
      - .env
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - myapp-network

volumes:
  postgres_data:

networks:
  myapp-network:
    driver: bridge