services:
  postgres:
    image: postgres:15-alpine
    container_name: myapp-postgres-prod
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - myapp-network-prod
    restart: unless-stopped

  server:
    build:
      context: ./packages/server
      dockerfile: Dockerfile
    container_name: myapp-server-prod
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: production
      SERVER_PORT: 3001
    networks:
      - myapp-network-prod
    restart: unless-stopped

  client:
    build:
      context: ./packages/client
      dockerfile: Dockerfile
      target: production
    container_name: myapp-client-prod
    ports:
      - "8080:80"
    depends_on:
      - server
    networks:
      - myapp-network-prod
    restart: unless-stopped

volumes:
  postgres_data_prod:

networks:
  myapp-network-prod:
    driver: bridge
