services:
  postgres:
    image: postgres:15-alpine
    container_name: myapp-postgres-prod
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
    networks:
      - myapp-network-prod
    restart: unless-stopped

  server:
    build:
      context: .
      dockerfile: ./packages/server/Dockerfile
      SERVER_PORT: ${SERVER_PORT}
    container_name: myapp-server-prod
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - postgres
    networks:
      - myapp-network-prod
    restart: unless-stopped

  client:
    build:
      context: ./packages/client
      dockerfile: Dockerfile
      target: production
    container_name: myapp-client-prod
    environment:
      CLIENT_PORT: ${CLIENT_PORT}
      SERVER_PROTOCOL: ${SERVER_PROTOCOL}
    ports:
      - "${CLIENT_PORT}:80"
    depends_on:
      - server
    networks:
      - myapp-network-prod
    restart: unless-stopped

networks:
  myapp-network-prod:
    driver: bridge
