services:
  postgres:
    image: postgres:15-alpine
    container_name: myapp-postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
    networks:
      - myapp-network

  server:
    build:
      context: .
      dockerfile: ./Dockerfile.server
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: myapp-server
    env_file:
      - .env
    environment:
      NODE_ENV: production
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      SERVER_PORT: ${SERVER_PORT}
      CLIENT_URL: ${CLIENT_URL}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - postgres
    networks:
      - myapp-network

networks:
  myapp-network:
    driver: bridge
