services:
  # База данных PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: myapp-postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - myapp-network

  # Серверное приложение
  server:
    build:
      context: .
      dockerfile: ./Dockerfile.server
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: myapp-server
    env_file:
      - .env
    environment:
      NODE_ENV: development
      POSTGRES_HOST: ${POSTGRES_HOST}
      SERVER_PORT: ${SERVER_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      CLIENT_URL: ${CLIENT_URL}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - postgres
    networks:
      - myapp-network

  # Клиентское приложение
  client:
    build:
      context: .
      dockerfile: ./Dockerfile.client
      target: development
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: myapp-client
    env_file:
      - .env
    ports:
      - "${CLIENT_PORT}:3000"
    depends_on:
      - server
    networks:
      - myapp-network

networks:
  myapp-network:
    driver: bridge
