services:
  # База данных PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: myapp-postgres
    environment:
      POSTGRES_DB: myapp_db
      POSTGRES_USER: myapp_user
      POSTGRES_PASSWORD: myapp_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - myapp-network

  # Серверное приложение
  server:
    build:
      context: /packages/server
      dockerfile: DockerFile
    container_name: myapp-server
    environment:
      DATABASE_URL: postgresql://myapp_user:myapp_password@postgres:5432/myapp_db
      NODE_ENV: development
    ports:
      - "3001:3001"
    volumes:
       - .:/app
       - /app/node_modules
       - /app/packages/server/node_modules
    depends_on:
      - postgres
    networks:
      - myapp-network
    command: yarn dev

  # Клиентское приложение
  client:
    build:
      context: packages/client
      dockerfile: DockerFile
    container_name: myapp-client
    environment:
      REACT_APP_API_URL: http://localhost:3001
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/packages/client/node_modules
    depends_on:
      - server
    networks:
      - myapp-network
    command: yarn start

volumes:
  postgres_data:

networks:
  myapp-network:
    driver: bridge
